[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  GENERATE_SOURCEMAP = "false"
  REACT_APP_SOCKET_URL = "https://radix-sort.onrender.com"
  CI = "false"
  
[build.production.environment]
  GENERATE_SOURCEMAP = "false"
  REACT_APP_SOCKET_URL = "https://radix-sort.onrender.com"
  CI = "false"
